USE [WinForm]
GO

/****** Object:  Table [dbo].[TBL_IRSALIYELER]    Script Date: 11/09/2014 01:30:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_IRSALIYELER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IRSALIYESERI] [nvarchar](5) NULL,
	[IRSALIYENO] [nvarchar](15) NULL,
	[FATURAID] [int] NULL,
	[CARIKODU] [nvarchar](30) NULL,
	[TARIHI] [datetime] NULL,
	[ACIKLAMA] [text] NULL,
	[SAVEUSER] [int] NULL,
	[SAVEDATE] [datetime] NULL,
	[EDITUSER] [int] NULL,
	[EDITDATE] [datetime] NULL,
 CONSTRAINT [PK_TBLIRSALIYELER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

